name: ossf-scorecard

on:
  schedule: [{ cron: "15 3 * * *" }]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scorecards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
